version: '3.1'

services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    ports:
      - 4001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    restart: always
    command: mysqld --sql_mode=""
    volumes:
      - ./data/mysql5:/var/lib/mysql

  slim3boilerplate:
    image: slim3boilerplate
    container_name: slim3boilerplate
    ports:
      - 4002:80
    volumes:
      - ./data/logs:/var/apache_logs/
      - ./src:/var/www/html
    restart: always
    depends_on:
      - mysql5
